src/main/java/edu/hm/hafner/coverage/Metric.java, src/test/java/edu/hm/hafner/coverage/AbstractNodeTest.java, src/test/java/edu/hm/hafner/coverage/MethodNodeTest.java, src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/jacocoTestReport.xml
The code coverage of a method, class, etc. should be computed with any of the coverage metrics LINE, BRANCH, or INSTRUCTION. E.g. in JaCoCo some synthetic methods will have no line coverage but an instruction coverage.
Fixes https://github.com/jenkinsci/code-coverage-api-plugin/issues/598
=> Compute coverage of nodes with either lines, branches, or instructions

src/main/java/edu/hm/hafner/coverage/Metric.java, src/main/java/edu/hm/hafner/coverage/Node.java, src/main/java/edu/hm/hafner/coverage/Value.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java
Summing up the complexities of all methods might be not a good metric for a project. It makes more sense to look at the maximum complexity of all methods.
=> Add maximum complexity of all methods as a metric

pom.xml, src/main/java/edu/hm/hafner/coverage/CyclomaticComplexity.java, src/main/java/edu/hm/hafner/coverage/Metric.java, src/main/java/edu/hm/hafner/coverage/Value.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java
Otherwise serialized instances are wrongly mapped.
=> Add metric parameter for `CyclomaticComplexity`

src/main/java/edu/hm/hafner/coverage/Coverage.java, src/main/java/edu/hm/hafner/coverage/CyclomaticComplexity.java, src/main/java/edu/hm/hafner/coverage/FractionValue.java, src/main/java/edu/hm/hafner/coverage/IntegerValue.java, src/main/java/edu/hm/hafner/coverage/Metric.java, src/main/java/edu/hm/hafner/coverage/Value.java, src/test/java/edu/hm/hafner/coverage/CoverageTest.java, src/test/java/edu/hm/hafner/coverage/CyclomaticComplexityTest.java, src/test/java/edu/hm/hafner/coverage/FractionValueTest.java, src/test/java/edu/hm/hafner/coverage/LinesOfCodeTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java
When validating quality gates the algorithm needs to know if a threshold is an upper or lower limit. Some metrics are better when the value is smaller (e.g., complexity) and other metrics are better when the value is larger (e.g. coverage percentage). The same information is required to render the delta values in green (good) or red (bad).
=> Add a metric tendency

Jenkinsfile, pom.xml, src/main/java/edu/hm/hafner/coverage/CoverageParser.java, src/main/java/edu/hm/hafner/coverage/FileNode.java, src/main/java/edu/hm/hafner/coverage/ModuleNode.java, src/main/java/edu/hm/hafner/coverage/Mutation.java, src/main/java/edu/hm/hafner/coverage/Node.java, src/main/java/edu/hm/hafner/coverage/PackageNode.java, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/main/java/edu/hm/hafner/coverage/parser/JacocoParser.java, src/main/java/edu/hm/hafner/coverage/parser/PitestParser.java, src/test/java/edu/hm/hafner/coverage/AbstractNodeTest.java, src/test/java/edu/hm/hafner/coverage/ContainerNodeTest.java, src/test/java/edu/hm/hafner/coverage/FileNodeTest.java, src/test/java/edu/hm/hafner/coverage/ModuleNodeTest.java, src/test/java/edu/hm/hafner/coverage/NodeTest.java, src/test/java/edu/hm/hafner/coverage/PackageNodeTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/coverage-missing-sources.xml
Replaces the path computation based on packages.
Fixes https://github.com/jenkinsci/code-coverage-api-plugin/issues/610
Tasks:
=> Add relative path for file nodes

src/main/java/edu/hm/hafner/coverage/parser/JacocoParser.java, src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/jacoco-jenkins.xml
See exception in https://github.com/jenkinsci/jenkins/pull/7831
JaCoCo reports can contain [groups](https://github.com/jacoco/jacoco/blob/31f16d834819526cf1e8ffbafed4b7e3fe5ed502/org.jacoco.report/src/org/jacoco/report/xml/report.dtd#L34-L37) as element below a report.
=> Add support for groups in JaCoCo files

src/main/java/edu/hm/hafner/coverage/Mutation.java
These strings are the same in a lot of mutations. Maybe we can switch to a `TreeString` in a future release of this model.
=> Intern all strings of a mutation

src/main/java/edu/hm/hafner/coverage/ModuleNode.java, src/main/java/edu/hm/hafner/coverage/Node.java, src/main/java/edu/hm/hafner/coverage/PackageNode.java, src/test/java/edu/hm/hafner/coverage/ModuleNodeTest.java, src/test/java/edu/hm/hafner/coverage/NodeTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/cobertura-merge-a.xml, src/test/resources/edu/hm/hafner/coverage/parser/cobertura-merge-b.xml, src/test/resources/edu/hm/hafner/coverage/parser/file-subpackage.xml
See jenkinsci/code-coverage-api#729
Tasks to do:
=> Merge all values of the hierarchy using `max`

src/main/java/edu/hm/hafner/coverage/FileNode.java, src/main/java/edu/hm/hafner/coverage/LineRange.java, src/test/java/edu/hm/hafner/coverage/CoverageParserTest.java, src/test/java/edu/hm/hafner/coverage/CoverageTest.java, src/test/java/edu/hm/hafner/coverage/FileNodeTest.java, src/test/java/edu/hm/hafner/coverage/IntegerValueTest.java, src/test/java/edu/hm/hafner/coverage/LineRangeTest.java, src/test/java/edu/hm/hafner/coverage/MetricTest.java, src/test/java/edu/hm/hafner/coverage/MutationStatusTest.java, src/test/java/edu/hm/hafner/coverage/MutationTest.java, src/test/java/edu/hm/hafner/coverage/NodeTest.java, src/test/java/edu/hm/hafner/coverage/SafeFractionTest.java, src/test/java/edu/hm/hafner/coverage/ValueTest.java
As requested, these are tests and implementations from some of the exercises during the testing-lecture (summer-semester 2023, University of Applied Sciences Munich):
A LineRange-class was implemented for grouping coverage-information for consecutive lines-of-code.
Various new tests improve overall line-, branch- and mutation-coverage for the project.
All tests (old and new) run successfully on my local system (based on current state of the main-branch in the official coverage-model-repository). 
```[tasklist]
```
=> Implemented LineRange-class and improved overall code-coverage

src/main/java/edu/hm/hafner/coverage/Coverage.java, src/main/java/edu/hm/hafner/coverage/FileNode.java, src/main/java/edu/hm/hafner/coverage/MethodNode.java, src/main/java/edu/hm/hafner/coverage/Node.java, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/test/java/edu/hm/hafner/coverage/NodeTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java
Merging is now based on the actual file counters. That means information below the files (classes and methods) needs to be stripped of. Additionally, the predefined counters of inner nodes (packages, etc.) will be removed as well since they might be inaccurate after a merge.
This works well for the line coverage but cannot work for the branch coverage as we cannot identify the branches during merge. 
Will (partly) fix https://github.com/jenkinsci/code-coverage-api-plugin/issues/729.
=> Rewrite merging of nodes

src/main/java/edu/hm/hafner/coverage/CoverageParser.java, src/main/java/edu/hm/hafner/coverage/Node.java, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/test/java/edu/hm/hafner/coverage/parser/AbstractParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/cobertura-duplicate-methods.xml, src/test/resources/edu/hm/hafner/coverage/parser/cobertura-missing-condition-coverage.xml
Add a new optional property to the parser to ignore all errors. Additionally, use a default value of 2/2 when branch coverage is missing the details attribute `condition-coverage`.
See https://github.com/jenkinsci/code-coverage-api-plugin/issues/785
=> Make `CoberturaParser` more robost on broken input files

src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/coverage/registry/ParserRegistryTest.java
Otherwise the coverage API cannot use the property.
Followup for https://github.com/jenkinsci/code-coverage-api-plugin/issues/785
=> Make `ProcessingMode` a parameter in the registry

src/main/java/edu/hm/hafner/coverage/ClassNode.java, src/main/java/edu/hm/hafner/coverage/Percentage.java, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/test/java/edu/hm/hafner/coverage/PercentageTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/cobertura-duplicate-classes.xml
Duplicate classes and methods now get a new generated suffix in the name to make them unique.
See https://github.com/jenkinsci/code-coverage-api-plugin/pull/788#issuecomment-1789752978
=> Ignore duplicate classes in Cobertura reports

doc/dependency-graph.puml, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java
Improve handling of duplicate classes and methods: even if the created reports are invalid or inconsistent, it makes sense to ignore those problems and create a valid model.
Also make sure that a query for a parser always uses uppercase.
=> Cleanup cobertura parser

.github/workflows/autograding.yml, doc/dependency-graph.puml, src/main/java/edu/hm/hafner/coverage/Node.java, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/coverage/NodeTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java
See https://issues.jenkins.io/browse/JENKINS-72310 for details.
=> Add support for merging a mixed set of different and equal modules

src/main/java/edu/hm/hafner/coverage/CoverageParser.java, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/main/java/edu/hm/hafner/coverage/parser/JacocoParser.java, src/main/java/edu/hm/hafner/coverage/parser/JunitParser.java, src/main/java/edu/hm/hafner/coverage/parser/PitestParser.java, src/test/java/edu/hm/hafner/coverage/parser/AbstractParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/JunitParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/PitestParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/cobertura/empty.xml, src/test/resources/edu/hm/hafner/coverage/parser/jacoco/empty.xml, src/test/resources/edu/hm/hafner/coverage/parser/junit/empty.xml, src/test/resources/edu/hm/hafner/coverage/parser/pit/empty.xml
Otherwise, the parsers will throw an exception.
Will fix jenkinsci/code-coverage-api-plugin#723.
See also https://issues.jenkins.io/browse/JENKINS-72449.
=> [JENKINS-72449] Add a toggle to ignore empty results

src/main/java/edu/hm/hafner/coverage/parser/OpenCoverParser.java, src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/coverage/parser/OpenCoverParserTest.java, src/test/java/edu/hm/hafner/coverage/registry/ParserRegistryTest.java, src/test/resources/edu/hm/hafner/coverage/parser/opencover/empty.xml, src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-empty-module.xml, src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-empty.xml, src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-missing-module-name.xml, src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-missing-source-line.xml, src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-reporttotestsourcefiles.xml, src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-withskippedmodules.xml, src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover.xml
Add parser for the OpenCover format that was supported by the `coverage-api` plugin through `opencover` plugin (https://plugins.jenkins.io/opencover/)
OpenCover is not actively maintained but still the reference for .NET SDK legacy project (https://github.com/OpenCover/opencover)
I tried to get inspired from the Jacoco and Cobertura Parser to implement it. I'm getting similar coverage percentage from the `opencover`
Automated only.
But when integrated to coverage plugin I will do more test with real data when migrating from `publishCoverage` to `recordCoverage` step.
```[tasklist]
```
=> Add support for OpenCover format

src/main/java/edu/hm/hafner/coverage/parser/NunitParser.java, src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/coverage/parser/NunitParserTest.java, src/test/java/edu/hm/hafner/coverage/registry/ParserRegistryTest.java, src/test/resources/edu/hm/hafner/coverage/parser/nunit/empty.xml, src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit-invalid-status.xml, src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit-no-failure-block.xml, src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit-no-message.xml, src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit.xml, src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit2-format.xml
Add test count metric for NUnit which is a famous test runner for .NET project (Similar to JUnit).
The XML format is somehow similar but different (different tag, attributes, or errors message stored deeper on the XML structure
It's possible there is duplicate between the JUnit and NUnit parser. We could perhaps move some utils to the parent class
- 100% test coverage
- Support of NUnit 2 and NUnit 3 format (https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html)
```[tasklist]
```
=> Add support for NUnit format

pom.xml, src/main/java/edu/hm/hafner/coverage/CoverageParser.java, src/main/java/edu/hm/hafner/coverage/parser/AbstractTestParser.java, src/main/java/edu/hm/hafner/coverage/parser/JunitParser.java, src/main/java/edu/hm/hafner/coverage/parser/NunitParser.java, src/main/java/edu/hm/hafner/coverage/parser/OpenCoverParser.java, src/test/java/edu/hm/hafner/coverage/parser/AbstractParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/OpenCoverParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-with-bom.xml
Remove some duplications in the test parsers.
=> Extract a common base class for test parsers

README.md, src/main/java/edu/hm/hafner/coverage/parser/XunitParser.java, src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/coverage/parser/XunitParserTest.java, src/test/java/edu/hm/hafner/coverage/registry/ParserRegistryTest.java, src/test/resources/edu/hm/hafner/coverage/parser/xunit/empty.xml, src/test/resources/edu/hm/hafner/coverage/parser/xunit/xunit-invalid-status.xml, src/test/resources/edu/hm/hafner/coverage/parser/xunit/xunit-no-failure-block.xml, src/test/resources/edu/hm/hafner/coverage/parser/xunit/xunit-no-message.xml, src/test/resources/edu/hm/hafner/coverage/parser/xunit/xunit.xml
Realized that I have some .NET project using XUnit .NET runner (https://xunit.net/) running instead of NUnit.
XML format is (again) a bit different (https://xunit.net/docs/format-xml-v2)
But very similar and can be integrated easily since https://github.com/jenkinsci/coverage-model/pull/70
Automated tests and tested with generated XML file on a sample .NET project
```
dotnet test --logger:"xunit;LogFilePath=xunit-result.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
```
Added 1 passed test, 1 skipped and 1 failure
```[tasklist]
```
=> Add support for XUnit .NET format

src/main/java/edu/hm/hafner/coverage/CoverageParser.java, src/main/java/edu/hm/hafner/coverage/parser/AbstractTestParser.java, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/main/java/edu/hm/hafner/coverage/parser/JacocoParser.java, src/main/java/edu/hm/hafner/coverage/parser/JunitParser.java, src/main/java/edu/hm/hafner/coverage/parser/NunitParser.java, src/main/java/edu/hm/hafner/coverage/parser/OpenCoverParser.java, src/main/java/edu/hm/hafner/coverage/parser/PitestParser.java, src/main/java/edu/hm/hafner/coverage/parser/XunitParser.java, src/test/java/edu/hm/hafner/coverage/parser/AbstractParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/JunitParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/NunitParserTest.java, src/test/java/edu/hm/hafner/coverage/parser/TestCaseMappingTest.java, src/test/java/edu/hm/hafner/coverage/parser/XunitParserTest.java
This helps to improve error detection in the consumers.
Before:
```
Quality Monitor Errors:
No data found in the specified file.
```
After:
```
Quality Monitor Errors:
The processed file 'empty.xml' does not contain data.
```
=> Add `fileName` as a parameter.

src/main/java/edu/hm/hafner/coverage/Node.java, src/test/java/edu/hm/hafner/coverage/parser/TestCaseMappingTest.java
The mapping is done by evaluating the name of the test class. If the name of the test class cannot be mapped to a target class, then the tests of this test class are ignored. All unmapped test classes will be retained so that they can be visualized differently.
=> Correctly merge test cases into the existing coverage tree

src/main/java/edu/hm/hafner/coverage/Node.java
The API is better usable with a type of `List<? extends Node>`.
=> Restore old API for `merge`

src/main/java/edu/hm/hafner/coverage/Node.java, src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/cobertura/cobertura-same-filename.xml, src/test/resources/edu/hm/hafner/coverage/parser/cobertura/merge-duplicate-a.xml, src/test/resources/edu/hm/hafner/coverage/parser/cobertura/merge-duplicate-b.xml
In #113 we replaced `name` with `id` when comparing nodes. It seems that we forgot to apply this behavioral change when merging nodes as well.
See https://issues.jenkins.io/browse/JENKINS-73352.
=> JENKINS-73325: Use ID when merging nodes

src/main/java/edu/hm/hafner/coverage/CoverageParser.java, src/main/java/edu/hm/hafner/coverage/parser/AbstractTestParser.java, src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java, src/main/java/edu/hm/hafner/coverage/parser/JacocoParser.java, src/main/java/edu/hm/hafner/coverage/parser/OpenCoverParser.java, src/main/java/edu/hm/hafner/coverage/parser/PitestParser.java, src/test/java/edu/hm/hafner/coverage/parser/AbstractParserTest.java
It makes no sense to reuse this exception, especially when there are non XML parsers used in the future.
=> Move the parsing exception to the model

pom.xml
Fix POM flattening configuration: now all artifacts are correctly added to the list of dependencies.
See [JENKINS-73663](https://issues.jenkins.io/browse/JENKINS-73663)
=> [JENKINS-73663] Fix pom flattening so that parent deps are included now

src/main/java/edu/hm/hafner/coverage/Metric.java, src/main/java/edu/hm/hafner/coverage/Node.java, src/test/java/edu/hm/hafner/coverage/MetricTest.java, src/test/java/edu/hm/hafner/coverage/parser/TestCaseMappingTest.java
When the test cases are mapped to the coverage tree then we should not ignore those tests that could not be automatically be mapped. It makes more sense to attach the correct metric value to the tree, even though the tests within the tree are smaller.
=> Retain the number of total tests after mapping the tests to classes

src/main/java/edu/hm/hafner/coverage/Metric.java, src/test/java/edu/hm/hafner/coverage/MetricTest.java
If the metric is omitted then the correct message should be shown.
=> Improve exception handling if metric is missing

src/main/java/edu/hm/hafner/coverage/Metric.java, src/test/java/edu/hm/hafner/coverage/MetricTest.java
Downstream tools will report the metrics in different user interfaces, so it makes sense to provide English display names in this library. Additional localizations should be possible, but are not yet provided here.
=> Add a displayName for each metric

pom.xml, src/main/java/edu/hm/hafner/coverage/Coverage.java, src/test/java/edu/hm/hafner/coverage/CoverageTest.java
Even if the coverage is not set, the object needs to be serialized.
=> Add serialization of the null object

src/main/java/edu/hm/hafner/coverage/parser/CloverParser.java, src/test/java/edu/hm/hafner/coverage/parser/CloverParserTest.java, src/test/resources/edu/hm/hafner/coverage/parser/clover/clover-empty-project-name.xml
In the Clover Parser the field projectName is now optional and will by default be set to "-".
An automated test where the previous name-setting functionality was tested could not be found.
Since the difference is minimal no additional automated test was written.
The logic of setting a default value when there is no name present has been tested in a separate environment.
Scenarios tested:
Optional name was missing (null) -> Default value was used.
Optional name was present -> Optional name was used.
[JENKINS-75648](https://issues.jenkins.io/browse/JENKINS-75648)
=> [JENKINS-75648] Make projectName optional in Clover Parser

src/main/java/edu/hm/hafner/coverage/Node.java, src/test/java/edu/hm/hafner/coverage/NodeTest.java, src/test/java/edu/hm/hafner/coverage/parser/CloverParserTest.java
Some parsers create file nodes with names that contain path elements. While this technically works, it pollutes the UI that renders the file names in several places. So it is helpful to clean up the file names while creating the tree.
This change will also fix [JENKINS-75684](https://issues.jenkins.io/browse/JENKINS-75684)
=> [JENKINS-75684] Rename broken file names
